//! Error types
use num_derive::FromPrimitive;
use num_traits::FromPrimitive;
use solana_program::program_error::PrintProgramError;
use solana_program::{decode_error::DecodeError, msg, program_error::ProgramError};
use thiserror::Error;

/// Errors that may be returned by the TokenSwap program.
#[derive(Clone, Debug, Eq, Error, FromPrimitive, PartialEq)]
pub enum CrateError {
    // 0.
    /// The account cannot be initialized because it is already being used.
    #[error("Swap account already in use")]
    AlreadyInUse,
    /// The program address provided doesn't match the value generated by the program.
    #[error("Invalid program address generated from bump seed and key")]
    InvalidProgramAddress,
    /// The owner of the input isn't set to the program address generated by the program.
    #[error("Input account owner is not the program address")]
    InvalidOwner,
    /// The owner of the pool token output is set to the program address generated by the program.
    #[error("Output pool account owner cannot be the program address")]
    InvalidOutputOwner,
    /// The deserialization of the account returned something besides State::Mint.
    #[error("Deserialized account is not an SPL Token mint")]
    ExpectedMint,

    // 5.
    /// The deserialization of the account returned something besides State::Account.
    #[error("Deserialized account is not an SPL Token account")]
    ExpectedAccount,
    /// The input token account is empty.
    #[error("Input token account empty")]
    EmptySupply,
    /// The pool token mint has a non-zero supply.
    #[error("Pool token mint has a non-zero supply")]
    InvalidSupply,
    /// The provided token account has a delegate.
    #[error("Token account has a delegate")]
    InvalidDelegate,
    /// The input token is invalid for swap.
    #[error("InvalidInput")]
    InvalidInput,

    // 10.
    /// Address of the provided swap token account is incorrect.
    #[error("Address of the provided swap token account is incorrect")]
    IncorrectSwapAccount,
    /// Address of the provided pool token mint is incorrect
    #[error("Address of the provided pool token mint is incorrect")]
    IncorrectPoolMint,
    /// The output token is invalid for swap.
    #[error("InvalidOutput")]
    InvalidOutput,
    /// General calculation failure due to overflow or underflow
    #[error("General calculation failure due to overflow or underflow")]
    CalculationFailure,
    /// Invalid instruction number passed in.
    #[error("Invalid instruction")]
    InvalidInstruction,

    // 15.
    /// Swap input token accounts have the same mint
    #[error("Swap input token accounts have the same mint")]
    RepeatedMint,
    /// Swap instruction exceeds desired slippage limit
    #[error("Swap instruction exceeds desired slippage limit")]
    ExceededSlippage,
    /// The provided token account has a close authority.
    #[error("Token account has a close authority")]
    InvalidCloseAuthority,
    /// The pool token mint has a freeze authority.
    #[error("Pool token mint has a freeze authority")]
    InvalidFreezeAuthority,
    /// The pool fee token account is incorrect
    #[error("Pool fee token account incorrect")]
    IncorrectFeeAccount,

    // 20.
    /// Given pool token amount results in zero trading tokens
    #[error("Given pool token amount results in zero trading tokens")]
    ZeroTradingTokens,
    /// The fee calculation failed due to overflow, underflow, or unexpected 0
    #[error("Fee calculation failed due to overflow, underflow, or unexpected 0")]
    FeeCalculationFailure,
    /// ConversionFailure
    #[error("Conversion to u64 failed with an overflow or underflow")]
    ConversionFailure,
    /// The provided fee does not match the program owner's constraints
    #[error("The provided fee does not match the program owner's constraints")]
    InvalidFee,
    /// The provided token program does not match the token program expected by the swap
    #[error("The provided token program does not match the token program expected by the swap")]
    IncorrectTokenProgramId,

    // 25.
    /// The provided curve type is not supported by the program owner
    #[error("The provided curve type is not supported by the program owner")]
    UnsupportedCurveType,
    /// The provided curve parameters are invalid
    #[error("The provided curve parameters are invalid")]
    InvalidCurve,
    /// The operation cannot be performed on the given curve
    #[error("The operation cannot be performed on the given curve")]
    UnsupportedCurveOperation,
}
impl From<CrateError> for ProgramError {
    fn from(e: CrateError) -> Self {
        ProgramError::Custom(e as u32)
    }
}
impl<T> DecodeError<T> for CrateError {
    fn type_of() -> &'static str {
        "Swap Error"
    }
}

impl PrintProgramError for CrateError {
    fn print<E>(&self)
    where
        E: 'static + std::error::Error + DecodeError<E> + PrintProgramError + FromPrimitive,
    {
        match self {
            CrateError::AlreadyInUse => msg!("Error: Swap account already in use"),
            CrateError::InvalidProgramAddress => {
                msg!("Error: Invalid program address generated from bump seed and key")
            }
            CrateError::InvalidOwner => {
                msg!("Error: The input account owner is not the program address")
            }
            CrateError::InvalidOutputOwner => {
                msg!("Error: Output pool account owner cannot be the program address")
            }
            CrateError::ExpectedMint => {
                msg!("Error: Deserialized account is not an SPL Token mint")
            }
            CrateError::ExpectedAccount => {
                msg!("Error: Deserialized account is not an SPL Token account")
            }
            CrateError::EmptySupply => msg!("Error: Input token account empty"),
            CrateError::InvalidSupply => msg!("Error: Pool token mint has a non-zero supply"),
            CrateError::RepeatedMint => msg!("Error: Swap input token accounts have the same mint"),
            CrateError::InvalidDelegate => msg!("Error: Token account has a delegate"),
            CrateError::InvalidInput => msg!("Error: InvalidInput"),
            CrateError::IncorrectSwapAccount => {
                msg!("Error: Address of the provided swap token account is incorrect")
            }
            CrateError::IncorrectPoolMint => {
                msg!("Error: Address of the provided pool token mint is incorrect")
            }
            CrateError::InvalidOutput => msg!("Error: InvalidOutput"),
            CrateError::CalculationFailure => msg!("Error: CalculationFailure"),
            CrateError::InvalidInstruction => msg!("Error: InvalidInstruction"),
            CrateError::ExceededSlippage => {
                msg!("Error: Swap instruction exceeds desired slippage limit")
            }
            CrateError::InvalidCloseAuthority => msg!("Error: Token account has a close authority"),
            CrateError::InvalidFreezeAuthority => {
                msg!("Error: Pool token mint has a freeze authority")
            }
            CrateError::IncorrectFeeAccount => msg!("Error: Pool fee token account incorrect"),
            CrateError::ZeroTradingTokens => {
                msg!("Error: Given pool token amount results in zero trading tokens")
            }
            CrateError::FeeCalculationFailure => msg!(
                "Error: The fee calculation failed due to overflow, underflow, or unexpected 0"
            ),
            CrateError::ConversionFailure => msg!("Error: Conversion to or from u64 failed."),
            CrateError::InvalidFee => {
                msg!("Error: The provided fee does not match the program owner's constraints")
            }
            CrateError::IncorrectTokenProgramId => {
                msg!("Error: The provided token program does not match the token program expected by the swap")
            }
            CrateError::UnsupportedCurveType => {
                msg!("Error: The provided curve type is not supported by the program owner")
            }
            CrateError::InvalidCurve => {
                msg!("Error: The provided curve parameters are invalid")
            }
            CrateError::UnsupportedCurveOperation => {
                msg!("Error: The operation cannot be performed on the given curve")
            }
        }
    }
}
